from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import json
import uvicorn
from azure.ai.projects import AIProjectClient
from openai import OpenAI
import requests
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from azure.monitor.opentelemetry import configure_azure_monitor
from opentelemetry.instrumentation.openai_v2 import OpenAIInstrumentor
from dotenv import load_dotenv
import os

# Import prompts - handle both local and Docker environments
try:
    from backend.prompts import (
        get_production_readiness_prompt,
    )
except ImportError:
    from prompts import (
        get_production_readiness_prompt,
    )

app = FastAPI(title="Solution Architect Agent API", version="1.0.0")

# Load environment variables
load_dotenv()

# Get environment variables for AI Project
endpoint = os.getenv("PROJECT_ENDPOINT")
model_deployment_name = os.getenv("MODEL_DEPLOYMENT_NAME")

# Get environment variables for AOAI Resource
aoai_endpoint = os.getenv("AOAI_ENDPOINT")

# Get backend URL for file downloads (default to localhost:8000)
backend_url = os.getenv("BACKEND_URL", "http://localhost:8000")

if not endpoint or not model_deployment_name:
    raise ValueError("PROJECT_ENDPOINT and MODEL_DEPLOYMENT_NAME must be set in environment")

# Initialize Azure AI Project client
project_client = AIProjectClient(
    credential=DefaultAzureCredential(),
    endpoint=endpoint,
)

token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
)

aoai_client = OpenAI(
    base_url=aoai_endpoint,
    api_key=token_provider,
    #default_headers={"api-version": "2024-08-01-preview"}
)

# Set up tracing (optional - only if Application Insights is configured)
try:
    connection_string = project_client.telemetry.get_application_insights_connection_string()
    os.environ["AZURE_TRACING_GEN_AI_CONTENT_RECORDING_ENABLED"] = "true"
    OpenAIInstrumentor().instrument()
    configure_azure_monitor(connection_string=connection_string)
    print("Application Insights tracing enabled")
except Exception as e:
    print(f"Application Insights not configured, tracing disabled: {e}")

# Get OpenAI client
#openai_client = project_client.get_openai_client(api_version="2024-02-01")
openai_client = project_client.get_openai_client(api_version="2024-08-01-preview")

# Add CORS middleware to allow frontend communication
frontend_url = os.getenv("FRONTEND_URL", "http://localhost:3000")
allowed_origins = ["http://localhost:3000", frontend_url] if frontend_url != "http://localhost:3000" else ["http://localhost:3000"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Data models
class Message(BaseModel):
    role: str  # "user" or "assistant"
    content: str
    timestamp: Optional[str] = None

class ChatRequest(BaseModel):
    messages: List[Message]
    stream: bool = False

class ChatResponse(BaseModel):
    message: Message
    conversation_id: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None

class ProductionReadinessRequest(BaseModel):
    service: str
    messages: List[Message] = []

@app.get("/")
async def root():
    """Health check endpoint"""
    return {
        "status": "Solution Architect Agent API is running", 
        "version": "1.0.0",
        "azure_ai_enabled": True
    }

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "healthy", "timestamp": "2025-08-21T00:00:00Z"}

@app.get("/api/download-file/{container_id}/{file_id}/{file_type}")
async def download_file(container_id: str, file_id: str, file_type: str):
    """
    Download a file generated by Code Interpreter
    """
    try:
        # Construct the REST API endpoint for container files
        endpoint = f"{aoai_endpoint}/containers/{container_id}/files/{file_id}/content"
        
        headers = {"Authorization": f"Bearer {token_provider()}", "Content-Type": "application/json"}
        params = {"api-version": "preview"}
        
        response = requests.get(endpoint, headers=headers, params=params, timeout=30)

        content_bytes = response.content
        content_type = "application/octet-stream"
        
        # initialize the file extension as a docx
        file_extension = "docx"
        if file_type == "excel":
            file_extension = "xlsx"

        return StreamingResponse(
            iter([content_bytes]),
            media_type=content_type,
            headers={"Content-Disposition": f'attachment; filename="checklist.{file_extension}"'}
        )
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))

# ============================================================================
# SIMPLE ENDPOINT - Uses LLM for everything, no structured outputs
# ============================================================================
@app.post("/api/production-readiness", response_model=ChatResponse)
async def production_readiness_simple(request: ProductionReadinessRequest):
    """
    Simple production readiness chat that lets the LLM handle everything.
    No structured outputs, no state management - just conversation history and a comprehensive prompt.
    """
    try:
        # Build conversation history
        conversation_messages = [
            {"role": "system", "content": get_production_readiness_prompt(request.service)}
        ]
        
        # Add all previous messages from the conversation
        for msg in request.messages:
            conversation_messages.append({
                "role": msg.role,
                "content": msg.content
            })

        # Get LLM response
        response = openai_client.chat.completions.create(
            model=model_deployment_name,
            messages=conversation_messages,
            temperature=1,
            max_completion_tokens=2000
        )
        
        assistant_response = response.choices[0].message.content
        
        # Check if the LLM triggered file generation
        # The LLM will output "GENERATE_FILE_TRIGGER: word" or "GENERATE_FILE_TRIGGER: excel" when ready
        if "generate_file_trigger:" in assistant_response.lower():
            # Extract file type from the trigger itself (not from elsewhere in the response)
            file_type = "word"  # default
            if "generate_file_trigger: excel" in assistant_response.lower():
                file_type = "excel"
            elif "generate_file_trigger: word" in assistant_response.lower():
                file_type = "word"
            
            # Remove the trigger from the response (handle both with and without brackets)
            clean_response = assistant_response.replace("GENERATE_FILE_TRIGGER: word", "").replace("GENERATE_FILE_TRIGGER: excel", "").replace("GENERATE_FILE_TRIGGER: [word]", "").replace("GENERATE_FILE_TRIGGER: [excel]", "").strip()
            
            # Check if the checklist is actually in the conversation (by looking for "Why Important" which appears in checklists)
            # This is sort of a hack, but solves the issue where if the user says something like "Just download the checklist as a word doc and don't show me the list", it will need this information
            # can do so "silently" without showing the user the list but still generating the list in this separate LLM call and pushing it on the chat history
            has_checklist = any("Why Important" in msg.get("content", "") for msg in conversation_messages if msg.get("role") != "system")
            
            # If no checklist in conversation, generate it now for the file
            if not has_checklist:
                print("No checklist found in conversation - generating internally for file export")
                
                # Make a separate call to generate the checklist
                checklist_prompt = """The user wants to export a production readiness checklist file. Generate a COMPLETE production readiness checklist for ALL Azure services discussed in our conversation.

CRITICAL: You MUST generate a complete checklist with real, specific items. Do NOT say items are unavailable.

For EACH service mentioned in our conversation, provide exactly 5 critical production readiness items.

Use this EXACT format for each service:

**[Service Name]**

**Item Name**
- Action description (specific actionable step - what to implement/configure)
- Why Important: [detailed explanation of why this matters for production]
- Learn more: [Full Microsoft Learn URL - https://learn.microsoft.com/...]

Example:
**Azure OpenAI**

**Authentication & Authorization**
- Ensure Azure Active Directory authentication is configured for API access
- Why Important: Protects against unauthorized access and ensures compliance with security policies
- Learn more: https://learn.microsoft.com/azure/ai-services/openai/how-to/managed-identity

**Rate Limiting & Quotas**
- Monitor and configure usage quotas to prevent throttling
- Why Important: Ensures predictable performance and cost control
- Learn more: https://learn.microsoft.com/azure/ai-services/openai/quotas-limits

[Continue with 3 more items for Azure OpenAI, then repeat for all other services]

NOW generate the COMPLETE checklist for ALL services with 5 items each:"""
                
                checklist_messages = conversation_messages.copy()
                checklist_messages.append({
                    "role": "user",
                    "content": checklist_prompt
                })
                
                # Calling LLM to generate internal checklist
                checklist_response = openai_client.chat.completions.create(
                    model=model_deployment_name,
                    messages=checklist_messages,
                    temperature=1,
                    max_completion_tokens=4000
                )
                
                checklist_content = checklist_response.choices[0].message.content
                
                # Add the checklist to conversation history for file generation
                conversation_messages.append({
                    "role": "assistant",
                    "content": checklist_content
                })
            
            # Add the assistant's original response to the conversation history
            conversation_messages.append({
                "role": "assistant",
                "content": assistant_response
            })
            
            # Format conversation history for the file generation agent
            conversation_summary = "Conversation History:\n\n"
            for msg in conversation_messages:
                if msg["role"] == "system":
                    continue  # Skip system prompt
                conversation_summary += f"{msg['role'].upper()}: {msg['content']}\n\n"
            
            # Implement Response API with Code Interpreter
            if file_type == "word":
                instructions = """You are a file generation agent. Generate a professional Word document (.docx) containing the production readiness checklist based on the conversation history provided.

**CRITICAL INSTRUCTIONS - READ CAREFULLY**:
1. The conversation history below contains the COMPLETE checklist content
2. You MUST extract and copy the EXACT text from the conversation - do NOT generate new content
3. Look for messages with "Why Important" - these contain the checklist items
4. Copy EXACTLY what you see in the conversation, including:
- All Azure services discussed
- Exact checklist item names as stated
- The action/description bullet point under each item name (e.g., "Ensure Azure Active Directory is used...")
- Complete "Why Important" descriptions
- ALL documentation URLs (Learn more links) - these MUST be included
- Implementation status (if the user went through systematic review)
- Any recommendations provided

The document should include:
1. Title: "Production Readiness Checklist for [Service Names]"
2. Executive summary paragraph
3. For EACH service, create a section with:
   - Service name as heading
   - Each checklist item with:
     * Item name (bold heading)
     * Action description (the bullet point that appears right after the item name - this is CRITICAL to include)
     * "Why Important:" followed by the exact importance text
     * "Learn more:" followed by the EXACT documentation URL from the conversation
     * Status (if reviewed): Implemented / Needs Attention / Not Applicable
     * Recommendations (if any)
4. Professional formatting with headers, bullet points, and proper spacing

**EXAMPLE FORMAT FROM CONVERSATION:**
```
Authentication & Authorization
- Ensure Azure Active Directory is used for API access.    <-- ACTION DESCRIPTION (MUST INCLUDE)
Why Important: Protects against unauthorized access...
Learn more: [URL]
```

**IMPORTANT**: 
- Do NOT paraphrase or recreate content
- Do NOT write placeholder text like "Checklist content would be listed here"
- ONLY include content that is ACTUALLY PRESENT in the conversation history below
- If you cannot find checklist items in the conversation, leave the sections empty rather than making up content

The conversation history is provided below. Extract all checklist items from it.

Use the python-docx library to create the document. Return the file when complete."""
            else:  # excel
                instructions = """You are a file generation agent. Generate a professional Excel spreadsheet (.xlsx) containing the production readiness checklist based on the conversation history provided.

**CRITICAL INSTRUCTIONS - READ CAREFULLY**:
1. The conversation history below contains the COMPLETE checklist content
2. You MUST extract and copy the EXACT text from the conversation - do NOT generate new content
3. Look for messages with "Why Important" - these contain the checklist items
4. Copy EXACTLY what you see in the conversation, including:
- All Azure services discussed
- Exact checklist item names as stated
- The action/description bullet point under each item name (e.g., "Ensure Azure Active Directory is used...")
- Complete "Why Important" descriptions
- ALL documentation URLs (Learn more links) - these MUST be included as separate cells
- Implementation status (if the user went through systematic review)
- Any recommendations provided

The spreadsheet should include:
1. Row 1: Title "Production Readiness Checklist for [Service Names]"
2. Row 3: Column headers: Service | Item | Action/Description | Why Important | Learn More (URL) | Status | Recommendations
3. Each checklist item as a row with:
   - Service name
   - Exact item name from conversation (e.g., "Authentication & Authorization")
   - Action description (the bullet point that appears right after the item name - CRITICAL to include)
   - Complete "Why Important" text
   - EXACT documentation URL from conversation
   - Status (if reviewed)
   - Recommendations (if any)
4. Professional formatting: bold headers, auto-sized columns, borders, frozen header row

**EXAMPLE FROM CONVERSATION:**
```
Authentication & Authorization
- Ensure Azure Active Directory is used for API access.    <-- ACTION/DESCRIPTION (MUST INCLUDE in separate column)
Why Important: Protects against unauthorized access...
Learn more: [URL]
```

**IMPORTANT**: 
- Do NOT paraphrase or recreate content
- Do NOT write placeholder text like "Checklist content would be listed here"
- ONLY include content that is ACTUALLY PRESENT in the conversation history below
- If you cannot find checklist items in the conversation, leave rows empty rather than making up content

The conversation history is provided below. Extract all checklist items from it.

Use the openpyxl library to create the spreadsheet. Return the file when complete."""
            
            # Use aoai_client for direct Azure OpenAI resource access (not AI Foundry Project)
            try:
                response = aoai_client.responses.create(
                    model=model_deployment_name,
                    tools=[
                        {
                            "type": "code_interpreter",
                            "container": {"type": "auto"}
                        }
                    ],
                    instructions=instructions,
                    input=conversation_summary,
                )
                print(f"DEBUG: Response created successfully")
            except AttributeError as ae:
                print(f"ERROR: aoai_client does not have 'responses' attribute: {ae}")
                raise HTTPException(status_code=500, detail=f"OpenAI client configuration error: {str(ae)}")
            except Exception as e:
                print(f"ERROR: Failed to create response with Code Interpreter: {type(e).__name__}: {str(e)}")
                import traceback
                print(f"ERROR TRACEBACK:\n{traceback.format_exc()}")
                raise HTTPException(status_code=500, detail=f"File generation failed: {str(e)}")
            
            # Extract file information from the response
            container_id = None
            file_id = None
            
            # Look for file annotations in the response
            for output in response.output:
                if output.type == "message":
                    for content in output.content:
                        if content.type == "output_text":
                            for annotation in content.annotations:
                                if annotation.type == "container_file_citation":
                                    container_id = annotation.container_id
                                    file_id = annotation.file_id
            
            file_url = f"{backend_url}/api/download-file/{container_id}/{file_id}/{file_type}" if file_id else None

            # Prepare the response message
            file_info = ""
            if file_url:
                file_info = f"\n\n📄 [Download your {file_type} file]({file_url})"
            else:
                file_info = f"\n\n📄 File generated successfully ({file_type} format)!"
            
            # If we generated an internal checklist, we need to inform the frontend about it
            # so it can be included in future conversation history
            final_content = f"{clean_response}{file_info}"
            if not has_checklist and 'checklist_content' in locals():
                # Prepend the internal checklist as a hidden prefix
                # The frontend should maintain this in conversation history but not display it
                final_content = f"[INTERNAL_CHECKLIST_START]\n{checklist_content}\n[INTERNAL_CHECKLIST_END]\n\n{clean_response}{file_info}"
            
            response_message = Message(
                role="assistant",
                content=final_content
            )
            
            return ChatResponse(
                message=response_message,
                conversation_id="production-readiness-simple",
                metadata={
                    "file_generation_requested": True, 
                    "file_type": file_type,
                    "file_id": file_id,
                    "file_url": file_url,
                    "has_hidden_checklist": not has_checklist and 'checklist_content' in locals()
                }
            )
        
        # Normal response (no file generation)
        response_message = Message(
            role="assistant",
            content=assistant_response
        )
        
        return ChatResponse(
            message=response_message,
            conversation_id="production-readiness-simple"
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error in simple production readiness chat: {str(e)}")

# ============================================================================
# STREAMING ENDPOINT - Streams LLM responses in real-time
# ============================================================================
@app.post("/api/production-readiness-simple-stream")
async def production_readiness_simple_stream(request: ProductionReadinessRequest):
    """
    Streaming version of the simplified production readiness chat.
    Streams LLM responses in real-time using Server-Sent Events (SSE).
    """
    async def generate_stream():
        try:
            # Build conversation history
            conversation_messages = [
                {"role": "system", "content": get_production_readiness_prompt(request.service)}
            ]
            
            # Add all previous messages from the conversation
            for msg in request.messages:
                conversation_messages.append({
                    "role": msg.role,
                    "content": msg.content
                })

            # Get LLM response with streaming
            stream = openai_client.chat.completions.create(
                model=model_deployment_name,
                messages=conversation_messages,
                temperature=1,
                max_completion_tokens=2000,
                stream=True
            )
            
            # Stream the chunks to the frontend
            for chunk in stream:
                if chunk.choices and len(chunk.choices) > 0:
                    delta = chunk.choices[0].delta
                    if hasattr(delta, 'content') and delta.content:
                        # Send chunk to frontend in SSE format
                        yield f"data: {json.dumps({'chunk': delta.content})}\n\n"
            
            # Send completion signal
            yield f"data: {json.dumps({'done': True})}\n\n"
            
        except Exception as e:
            # Send error to frontend
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
    
    return StreamingResponse(
        generate_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
        }
    )

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)